//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sven_Bobrowski.DE.MP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sven_Bobrowski.DE.MP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Assign new database.
        /// </summary>
        internal static string DB_AskToAssign_Caption {
            get {
                return ResourceManager.GetString("DB_AskToAssign_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Should the new database used as default database now?.
        /// </summary>
        internal static string DB_AskToAssign_Text {
            get {
                return ResourceManager.GetString("DB_AskToAssign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Assign existing database.
        /// </summary>
        internal static string DB_OpenDBToAssign_Caption {
            get {
                return ResourceManager.GetString("DB_OpenDBToAssign_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Database (*.db)|*.db.
        /// </summary>
        internal static string DB_OpenDBToAssign_Filter {
            get {
                return ResourceManager.GetString("DB_OpenDBToAssign_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder bearbeiten.
        /// </summary>
        internal static string Decoder_Caption_ModeEdit {
            get {
                return ResourceManager.GetString("Decoder_Caption_ModeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Decoder.
        /// </summary>
        internal static string Decoder_Caption_ModeNew {
            get {
                return ResourceManager.GetString("Decoder_Caption_ModeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückmeldemodul.
        /// </summary>
        internal static string DecoderType_Feedback {
            get {
                return ResourceManager.GetString("DecoderType_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lichtdecoder.
        /// </summary>
        internal static string DecoderType_Light {
            get {
                return ResourceManager.GetString("DecoderType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaldecoder.
        /// </summary>
        internal static string DecoderType_Signal {
            get {
                return ResourceManager.GetString("DecoderType_Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standarddecoder.
        /// </summary>
        internal static string DecoderType_Standard {
            get {
                return ResourceManager.GetString("DecoderType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichendecoder (Motorisch).
        /// </summary>
        internal static string DecoderType_Switch_Motor {
            get {
                return ResourceManager.GetString("DecoderType_Switch_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichendecoder (Servo).
        /// </summary>
        internal static string DecoderType_Switch_Servo {
            get {
                return ResourceManager.GetString("DecoderType_Switch_Servo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag bearbeiten.
        /// </summary>
        internal static string Item_Caption_ModeEdit {
            get {
                return ResourceManager.GetString("Item_Caption_ModeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Eintrag.
        /// </summary>
        internal static string Item_Caption_ModeNew {
            get {
                return ResourceManager.GetString("Item_Caption_ModeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC Standard.
        /// </summary>
        internal static string Protocol_DCC {
            get {
                return ResourceManager.GetString("Protocol_DCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loconet.
        /// </summary>
        internal static string Protocol_Loconet {
            get {
                return ResourceManager.GetString("Protocol_Loconet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorola.
        /// </summary>
        internal static string Protocol_Motorola {
            get {
                return ResourceManager.GetString("Protocol_Motorola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiformat.
        /// </summary>
        internal static string Protocol_Multi {
            get {
                return ResourceManager.GetString("Protocol_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückmelder S88 Bus.
        /// </summary>
        internal static string Protocol_S88 {
            get {
                return ResourceManager.GetString("Protocol_S88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frei.
        /// </summary>
        internal static string State_Combox_Free {
            get {
                return ResourceManager.GetString("State_Combox_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesperrt.
        /// </summary>
        internal static string State_Combox_Locked {
            get {
                return ResourceManager.GetString("State_Combox_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belegt.
        /// </summary>
        internal static string State_Combox_Occupied {
            get {
                return ResourceManager.GetString("State_Combox_Occupied", resourceCulture);
            }
        }
    }
}
